eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: students
            uri: http://localhost:8080
            predicates:
              - Path=/api/V1/students
              - Path=/api/V1/students/**
          - id: schools
            uri: http://localhost:8070
            predicates:
              - Path=/api/V1/schools/**
server:
  port: 8222
management:
  tracing:
    sampling:
      probabilty: 1.0