eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: schools
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/schools
    username: myuser
    password: mypassword
    jpa:
      hibernate:
        ddl-auto: none
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    students-url: http://localhost:8080/api/V1/students


server:
  port: 8070
management:
  tracing:
    sampling:
      probabilty: 1.0